// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_fGg6Wa4VkwUl1iNFr0AQjY3V3xg968Y',
    appId: '1:876084334075:web:a13f81091ef092263d8f5e',
    messagingSenderId: '876084334075',
    projectId: 'e-commerce-f834c',
    authDomain: 'e-commerce-f834c.firebaseapp.com',
    storageBucket: 'e-commerce-f834c.firebasestorage.app',
    measurementId: 'G-E2C5863985',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMHadd1_0rCPjQ0vGRPC2BnvqFWfgo7AI',
    appId: '1:876084334075:android:ba82deb05c937e323d8f5e',
    messagingSenderId: '876084334075',
    projectId: 'e-commerce-f834c',
    storageBucket: 'e-commerce-f834c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqLGHAj5m3XAgDpb-8jBzljeuQAucb9CM',
    appId: '1:876084334075:ios:6022360819f3fab43d8f5e',
    messagingSenderId: '876084334075',
    projectId: 'e-commerce-f834c',
    storageBucket: 'e-commerce-f834c.firebasestorage.app',
    iosClientId: '876084334075-dn6uvc1qgofoqbuq16p0mc8uok8u11bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarhanaciyasarmobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtXOCoFz0Av2pnUNRxHWEOyT96vzpc9J8',
    appId: '1:474845495952:ios:af2ae63522214e1d3b4e15',
    messagingSenderId: '474845495952',
    projectId: 'tarhanaci-yasar',
    storageBucket: 'tarhanaci-yasar.firebasestorage.app',
    androidClientId: '474845495952-utj6km4drgplub2ft5ao86390bei6a81.apps.googleusercontent.com',
    iosClientId: '474845495952-pl5ffdmsopf2tmh1r2879n07hcp2p8rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRBCFEz6A4CdBq-KEyAuErfjOGw8OHyo0',
    appId: '1:474845495952:web:00c4d7386fdac5d83b4e15',
    messagingSenderId: '474845495952',
    projectId: 'tarhanaci-yasar',
    authDomain: 'tarhanaci-yasar.firebaseapp.com',
    storageBucket: 'tarhanaci-yasar.firebasestorage.app',
    measurementId: 'G-KBQZKHQEDW',
  );

}